class ExampleDecryptDataAction extends baseAction {
  async executeMethod() {
    /*
    DECRYPT DATA EXAMPLE

    Steps:
    1. Make sure you have Encrypted Data which is generated by the encryptData API.
    2. Go through the encryption.lib.js helper method, created under the library/helperLib.
    3. You can use the same snippet for future use.
    4. The data sent by the user would decrypt using the decryptText() method.
    5. The encrypted  data should be sent in 'data' parameter in request params, as shown below.
          data:  26mxjRXwmPVw7goGnnPxrcfTYWncNv50FJmPY5uFCgY= 
    6. The decrypted data will be returned in the response.
          {"name":"NJS2-user"}

    */

    let { data } = this;
    const [encryptionLib] = AutoLoad.loadLibray("helperLib", ["encryption"]);
    this.setResponse("SUCCESS");
    return encryptionLib.decryptText(data);
  }
}
module.exports = ExampleDecryptDataAction;
